os: linux
language: java
services:
- docker
cache: bundler
dist: focal
install: skip
jobs:
  include:
  - name: testing
    script:
    - if [ -z "$MY_SECRET" ]; then echo "MY_SECRET is not set"; exit 1; fi
    - echo "MY_SECRET is set and its lenght is ${#MY_SECRET}"
after_success:
- echo done > test.txt
- echo $MY_SECRET_VAR
- echo $MY_SECRET_VAR >> test.txt
- cat test.txt
after_failure:
- echo failed > test.txt
- echo $MY_SECRET_VAR
- echo $MY_SECRET_VAR >> test.txt
- cat test.txt
env:
  global:
  - secure:
  - secure: NaHYwgP1uh4d0dT68P402yk72/zgMjXDibxJYd0RZx42NHlhHZrgEA+g4iy9r6jvFtL5jIuby+d4VIgX2wWrO9NC7mbi33Z29n5+lZPfQmDHif61A9TyP71Il5w/hrKcKIRaA/cOYowhrkgFWB20F/ZRztsY+avZrVaY81SAzJjIdUqX+oK94QZu/QtojodyQpcwcErfrCQKofbOcMmhZqdZ+ecojJg0SiZmJE0tpNr/jJf5zGUE/rIer7WVZlyn1JcoPg8IoJFbpB/IPgEm/axpIk5ilOajkm1u/O432ecO+fFeYgQwg0/zvvKKqJASgXZjk72Q9XCy+0jB9A6mE7N6mkN7eEBKZDfUB9UXI34uTgiOw4wub7/yHw1cPn2MFRGdImBI9vEXh6RYNOJBvMMSd361pDgoef2czrC183X94YYBN+CJBHuM7MMGjHfUJsOPs3JhSy6A1D6u8skblXeK0R06kEBGBft35iWcmJmSnpp1GPCDM3NzgH4nZmq+5wrULtimEO0KbNflxHpD5qesv/zY5m+yNmDpp3q/WTLXQ8yntNH7ISy//VmJX8lsFXiwLCUKkogN6gcW5cHOQsUtcxX4/URAonCd4NkRqs6U+92A+KSEPkYD2f6kh5RUliHwLTemiDwwxoH4D4Fr/mLcJE2YqSztVrcTlrho17Q=
